<?php
    //? |-----------------------------------------------------------------------------------------------|
    //? |  /lib/logParser.php                                                                           |
    //? |                                                                                               |
    //? |  Copyright (c) 2018-2019 Belikhun. All right reserved                                         |
    //? |  Licensed under the MIT License. See LICENSE in the project root for license information.     |
    //? |-----------------------------------------------------------------------------------------------|
    /**
     * A module to parse Themis generated log files
     * 
     * @package logParser
     */

    require_once $_SERVER["DOCUMENT_ROOT"]."/lib/belibrary.php";

    /**
     * Parse all the log file
     */
    define("LOGPARSER_MODE_FULL", "f");

    /**
     * Parse the log filename and header only
     */
    define("LOGPARSER_MODE_MINIMAL", "m");

    class logParser {

        /**
         *
         * Parse the log file generated by Themis
         *
         * @param    filePath   Path to log file
         * @return   Array      Contains parsed data
         *
         */
        public function __construct(String $filePath, String $mode = LOGPARSER_MODE_MINIMAL) {

        }
    }